version: "3.3"
services:
  angular:
    container_name: angular
    build:
      context: .
      dockerfile: ./docker/angular.Dockerfile
    ports:
      - "4200:4200"
    env_file: .env
    networks:
      - backend
    volumes:
      - './:/usr/src/app'
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      - angular
networks:
  backend:
    driver: bridge
