version: "3.8"

services:
  selenium:
    image: selenium/hub
    container_name: selenium
    privileged: true
    expose:
      - 4444
    # ports:
    #   - "4444:4444"
    environment:
      - GRID_HUB_PORT=4444
    networks:
      - backend

  chrome:
    image: selenium/node-chrome
    container_name: chrome
    privileged: true
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium
    expose:
      - 5555
      - 5900
    # ports:
    #   - "5555:5555"
    #   - "5900:5900"
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - backend

  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - backend

  angular:
    container_name: angular
    build:
      context: .
      dockerfile: ./docker/angular.Dockerfile
    ports:
      - "4200:4200"
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - backend
    depends_on:
      - chrome
      - redis

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certificates/server.crt:/etc/nginx/ssl/server.crt
      - ./docker/certificates/server.key:/etc/nginx/ssl/server.key
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      - angular

networks:
  backend:
    driver: bridge
